[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
working_directory = "./MailManager.Api"
startCommand = "dotnet MailManager.Api.dll"
restartPolicyType = "always"
healthcheckPath = "/health"